#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define WIFI_SSID "Harsha"
#define WIFI_PASSWORD "harshawifi"
#define WIFI_TIMEOUT_MS 10000

#define SERVER_HOSTNAME "tts.lora.local"
#define SERVER_IP "192.168.1.3"
#define SERVER_PORT_HTTP 8080
#define SERVER_PORT_HTTPS 8443
#define SERVER_PORT_MQTT 1883
#define SERVER_PORT_MQTTS 8883

#define UART_ID uart0
#define UART_BAUD_RATE 9600
#define UART_TX_PIN 0
#define UART_RX_PIN 1

#define Fm 100
#define SAMPLING_FACTOR 5
#define Fs (Fm << SAMPLING_FACTOR)
#define CLOCK_DIV (48000000 / Fs)

#define DMA_BUFFER_SIZE 640
#define HTTP_CONTENT_LENGTH "1280"
#define MAX_DATA_LENGTH 1536

#define BASE_PATH "/f1/"
#define CLIENT_ID "S001"
#define UPLOAD_PATH BASE_PATH CLIENT_ID

#define HTTP_HEADER "POST " UPLOAD_PATH " HTTP/1.1\r\n"\
                    "Host: " SERVER_HOSTNAME "\r\n"\
                    "Content-Type: application/octet-stream\r\n"\
                    "Content-Length: " HTTP_CONTENT_LENGTH "\r\n\r\n"

#define CA_CERT "-----BEGIN CERTIFICATE-----\n\
MIIDkzCCAnugAwIBAgIUGaBA3xnkmO1SHvu4cwb54FDaRCMwDQYJKoZIhvcNAQEL\n\
BQAwWTELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCVRBTUlMTkFEVTEQMA4GA1UEBwwH\n\
Q0hFTk5BSTENMAsGA1UECgwESUlUTTEVMBMGA1UEAwwMSUlUTSBMT1JBIENBMB4X\n\
DTI0MDQwODA5MjU1MFoXDTI1MDQwODA5MjU1MFowWTELMAkGA1UEBhMCSU4xEjAQ\n\
BgNVBAgMCVRBTUlMTkFEVTEQMA4GA1UEBwwHQ0hFTk5BSTENMAsGA1UECgwESUlU\n\
TTEVMBMGA1UEAwwMSUlUTSBMT1JBIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\n\
MIIBCgKCAQEAnfjtoaxWBixoz0K4O6Lw+cpIWXE6AwAQqbPQC8Gjo4RHGpuaBH/w\n\
iaYhLKBgga1n5DQLQerJoUnp1cCHI1iqeqPuej7m9PGGBz3DvJEjwu9f9legb2T1\n\
OcEjNF9QSPP6w1gADGoJL7O+R2PhTnxKUnB10PmBEgrNfWRiqZ5o2BbF7HriVgCL\n\
SAJnsJ69wXYYhEr4URrEzdjY9bEu0N4s2GDKKIR/rveJUgj6xh4LDSCkCH1u7Eh8\n\
gHJLxj/D4cgevqVNzs7kcQ0RrovlH6dwGwFUttK1I8qDAQ0QrShjnG10lwGnkHUh\n\
GqxhTqZAtdhNASD6z56EG+S76d7/7K3StwIDAQABo1MwUTAdBgNVHQ4EFgQUzcLd\n\
vMVVVVMJl9fLv2DXrw3j62cwHwYDVR0jBBgwFoAUzcLdvMVVVVMJl9fLv2DXrw3j\n\
62cwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAgrnSj0LQm7QD\n\
ur4ZaUTRwoZrFbDsvZ8vXYSnrf/Uvlc6nY5j5EO1/phxaJlTuULyGgXhujKTVsN6\n\
S0EHO9kGMQhQL+gTcN01Njhbqi3ax9kmod5Qep+b4Yis+OZNxMxeauSHUgaSIFkm\n\
ZZ8HbxSx6E7tyFspoiQ2Wu8BXgO29Fo4hUt19Wwium2dKzlH5ocQ/KtEhIUdytFs\n\
6ESRMGK6cgXRyA3l6MQaTvkG2mZwzMLHLE9xHAb9pAtkujbSrPE6GG5Qn9mdIOp1\n\
R2fN4R5SJfir6f8rYN3+yxtd4VfDJO7kFYiBNSIjpzvkohpJEXWEuwfvDVDHENTs\n\
1hkdpWdUfA==\n\
-----END CERTIFICATE-----\n"

#endif
